environment: qa
onDemandSuffix:

name: shop-test

shop:
  server:
    host: "http://shop-service"
    port: 80
    baseApiUrl: /api/v1/shop

test:
  tag: "TEST_TAG"
  pkg: "TEST_PACKAGE"

image:
  name: shop-test
  version: latest
