name: CI - basic verification

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Gather runtime environment versions - asdf
        uses: endorama/asdf-parse-tool-versions@v1
        id: versions

      - uses: actions/setup-java@v4
        with:
          java-version: "${{ env.JAVA_VERSION }}"
      - run: java --version

      - uses: s4u/setup-maven-action@v1.11.0
        with:
          java-version: "${{ env.JAVA_VERSION }}"
          maven-version: "${{ env.MVN_VERSION }}"
      - run: mvn --version

      - name: Build
        run: |
          mvn clean package -DskipTests
